import Link from "next/link";
import {PageHead,ProgressCard} from "./RoleUI";
import {StatStrip} from "./DrillUI";

const money=(n:number)=>`৳${Math.round(n).toLocaleString()}`;
export function RetailerDetailView({d,month,backHref}:{d:any;month:string;backHref:string}){
 const r=d.retailer;
 return <main className="page field-page"><PageHead eyebrow="Retailer Detail" title={r.retailerName||r.retailerCode} subtitle={`${r.retailerCode} · ${r.employee?.name||"Unassigned RSO"}` } action={<div className="drill-actions"><Link className="btn btn-ghost" href={backHref}>Back</Link><Link className="btn btn-soft" href={`?month=${month}`}>{month}</Link></div>}/>
 <StatStrip items={[{label:"GA Total",value:d.ga.length},{label:"150",value:d.ga150},{label:"300",value:d.ga300},{label:"Opening Balance",value:d.ob?money(Number(d.ob.amount)):"—"}]}/>
 <section className="section"><div className="progress-grid"><ProgressCard title="C2C" value={Math.round(d.c2cAmount)} target={0} unit="৳" note={`${d.c2cTrx} transaction days`}/><ProgressCard title="C2S" value={Math.round(d.c2sAmount)} target={500} unit="৳" note={`${d.c2sTrx} / 7 transactions`}/></div></section>
 <StatStrip items={[{label:"SSO",value:(r.simSeller||"").toUpperCase()==="Y"?`${d.ga.length} / 2 GA`:"Not SIM Seller",good:(r.simSeller||"").toUpperCase()==="Y"?d.ssoComplete:undefined},{label:"LSO",value:`${money(d.c2sAmount)} · ${d.c2sTrx} trx`,good:d.lsoComplete},{label:"Category",value:r.category||"—"},{label:"Route",value:r.route||"—"}]}/>
 <section className="section"><div className="section-head"><h2 className="section-title">Retailer information</h2></div><div className="card detail-meta-card"><Meta label="RSO" value={r.employee?.name||"Unassigned"}/><Meta label="RSO MSISDN" value={r.employee?.rsoMsisdn||r.iTopUpSrNumber||"—"}/><Meta label="Supervisor" value={r.employee?.supervisor?.name||"—"}/><Meta label="iTopUp Number" value={r.iTopUpNumber||"—"}/><Meta label="SIM Seller" value={r.simSeller||"—"}/><Meta label="BP Status" value={d.bp?`Active BP · ${d.bp.employee.name}`:"Normal retailer"}/></div></section>
 <section className="section"><div className="section-head"><h2 className="section-title">Recent GA</h2><span className="section-link">{month}</span></div><div className="card panel activity-list">{d.ga.length?d.ga.slice(0,20).map((x:any)=><div className="activity-row" key={x.simNo}><div><div className="activity-date">SIM {x.simNo}</div><div className="activity-meta">{x.activationDate.toISOString().slice(0,10)}{x.activationTime?` · ${x.activationTime}`:""}</div></div><div className="activity-value">৳{Number(x.sellingPrice)}<div className="mini-label">{Number(x.sellingPrice)===170?"150":"300"}</div></div></div>):<div className="empty">No GA in this month.</div>}</div></section>
 <section className="section"><div className="section-head"><h2 className="section-title">Recent recharge activity</h2></div><div className="card panel activity-list">{[...d.c2c.map((x:any)=>({type:"C2C",date:x.date,amount:Number(x.amount),trx:x.transactionCount})),...d.c2s.map((x:any)=>({type:"C2S",date:x.date,amount:Number(x.amount),trx:x.transactionCount}))].sort((a:any,b:any)=>b.date.getTime()-a.date.getTime()).slice(0,24).map((x:any,idx:number)=><div className="activity-row" key={`${x.type}-${x.date}-${idx}`}><div><div className="activity-date">{x.type}</div><div className="activity-meta">{x.date.toISOString().slice(0,10)} · {x.trx} trx</div></div><div className="activity-value">{money(x.amount)}</div></div>)}</div></section>
 </main>
}
function Meta({label,value}:{label:string;value:string}){return <div className="detail-meta-row"><span>{label}</span><strong>{value}</strong></div>}
