import type {ReactNode} from "react";
import Link from "next/link";
import {Icon} from "./icons";

export function PageHead({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action?:ReactNode}){return <header className="page-header role-head"><div><div className="eyebrow">{eyebrow}</div><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p></div>{action&&<div className="header-actions">{action}</div>}</header>}
export function Metric({label,value,sub,progress,icon="chart"}:{label:string;value:string|number;sub?:string;progress?:number;icon?:string}){return <div className="role-metric card"><div className="metric-icon"><Icon name={icon}/></div><div className="metric-label">{label}</div><div className="metric-value">{value}</div>{sub&&<div className="metric-sub">{sub}</div>}{typeof progress==="number"&&<div className="progress metric-progress"><span style={{width:`${Math.min(100,Math.max(0,progress))}%`}}/></div>}</div>}
export function ProgressCard({title,value,target,unit="",note}:{title:string;value:number;target:number;unit?:string;note?:string}){const p=target?Math.round(value/target*100):0;return <div className="card progress-card"><div className="progress-card-top"><div><div className="metric-label">{title}</div><div className="progress-number">{unit}{value.toLocaleString()}</div></div><span className={`status-pill ${p>=80?"status-good":p>=50?"status-mid":"status-low"}`}>{p}%</span></div><div className="progress"><span style={{width:`${Math.min(100,p)}%`}}/></div><div className="progress-card-foot"><span>Target {unit}{target.toLocaleString()}</span><span>{note||`${unit}${Math.max(0,target-value).toLocaleString()} remaining`}</span></div></div>}
export function QuickAction({href,label,icon}:{href:string;label:string;icon:string}){return <Link href={href} className="quick-action card role-quick"><span className="quick-icon"><Icon name={icon}/></span><span className="quick-label">{label}</span></Link>}
export function PersonList({title,items}:{title:string;items:Array<{name:string;meta:string;right:string;status?:string}>}){return <section className="section"><div className="section-head"><h2 className="section-title">{title}</h2><span className="section-link">View all</span></div><div className="card panel"><div className="team-list">{items.map((i,idx)=><div className="team-row" key={i.name+idx}><div className="team-person"><div className="person-avatar">{i.name.slice(0,2).toUpperCase()}</div><div><div className="person-name">{i.name}</div><div className="person-meta">{i.meta}</div></div></div><div style={{textAlign:"right"}}><div className="mini-value">{i.right}</div>{i.status&&<div className="mini-label">{i.status}</div>}</div></div>)}</div></div></section>}
export function SearchBar({placeholder="Search"}:{placeholder?:string}){return <div className="search-box"><Icon name="search"/><input placeholder={placeholder}/></div>}
export function InfoBanner({children}:{children:ReactNode}){return <div className="info-banner"><div className="info-dot"/><div>{children}</div></div>}
