"use client";
import {useEffect,useMemo,useState} from "react";
import {useCan} from "../components/PermissionContext";
import {dhakaMonth} from "../../lib/business-time";
import {TableScrollHint} from "../components/TableScrollHint";
import {PremiumFeedback} from "../components/PremiumFeedback";

type TargetRow={employeeId:string;employeeCode:string|null;rsoMsisdn:string;name:string;supervisor:string;retailerCount:number;gaTarget:number;c2cTarget:number;scTarget:number;totalRechargeTarget:number;ssoTarget:number;lsoTarget:number;scAchieved:number};
type BpRow={assignmentId:string;bpCode:string;bpName:string;rsoName:string;rsoMsisdn:string;gaTarget:number};
const numericFields=["gaTarget","c2cTarget","scTarget","totalRechargeTarget","ssoTarget","lsoTarget","scAchieved"] as const;
function currentMonth(){return dhakaMonth()}
export default function TargetsPage(){
  const canView=useCan("targets","view");
 const canUpdate=useCan("targets","update"),[month,setMonth]=useState(currentMonth()),[rows,setRows]=useState<TargetRow[]>([]),[bpRows,setBpRows]=useState<BpRow[]>([]);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[file,setFile]=useState<File|null>(null),[uploading,setUploading]=useState(false),[uploadResult,setUploadResult]=useState<any>(null);
 async function load(){setLoading(true);const r=await fetch(`/api/targets?month=${month}`,{cache:"no-store"});const d=await r.json();if(r.ok){setRows(d.rows||[]);setBpRows(d.bpRows||[])}else setMessage(d.error||"Could not load targets");setLoading(false)}
 useEffect(()=>{void load()},[month]);
 function update(i:number,k:typeof numericFields[number],v:string){const n=Math.max(0,Number(v)||0);setRows(old=>old.map((r,x)=>{if(x!==i)return r;const next={...r,[k]:n};if((k==="c2cTarget"||k==="scTarget")&&(!r.totalRechargeTarget||r.totalRechargeTarget===r.c2cTarget+r.scTarget))next.totalRechargeTarget=(k==="c2cTarget"?n:r.c2cTarget)+(k==="scTarget"?n:r.scTarget);return next}))}
 async function save(){setSaving(true);setMessage("");const r=await fetch("/api/targets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({month,rows,bpRows})});const d=await r.json();setSaving(false);setMessage(r.ok?`Saved targets for ${month}.`:d.error||"Save failed");if(r.ok)await load()}
 async function upload(){if(!file)return;setUploading(true);setUploadResult(null);setMessage("Reading target file...");const fd=new FormData();fd.append("file",file);fd.append("month",month);const r=await fetch("/api/targets/import",{method:"POST",body:fd});const d=await r.json();setUploading(false);if(!r.ok){setMessage(d.error||"Target import failed");return}setUploadResult(d);setMessage(`Target upload complete: ${d.updated} updated, ${d.failed} failed.`);setFile(null);await load()}
 const visible=useMemo(()=>{const q=search.toLowerCase().trim();return rows.filter(r=>!q||`${r.name} ${r.rsoMsisdn} ${r.employeeCode||""} ${r.supervisor}`.toLowerCase().includes(q))},[rows,search]);
 const totals=useMemo(()=>rows.reduce((a,r)=>({ga:a.ga+r.gaTarget,c2c:a.c2c+r.c2cTarget,sc:a.sc+r.scTarget,recharge:a.recharge+r.totalRechargeTarget,sso:a.sso+r.ssoTarget,lso:a.lso+r.lsoTarget}),{ga:0,c2c:0,sc:0,recharge:0,sso:0,lso:0}),[rows]);
  if(!canView)return null;
 return <main className="page target-center">
  <section className="target-v3-hero"><div><div className="admin-kicker">TARGET MANAGEMENT</div><h1>Monthly Target Control</h1><p>Set RSO and BP goals, import target workbooks and adjust values from one controlled workspace.</p><div className="target-v3-chips"><span>{rows.length} RSOs</span><span>{bpRows.length} BPs</span><span>Auto recharge calculation</span></div></div><label className="target-month target-v3-month"><span>TARGET MONTH</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></section>
  <div className="target-premium-workspace">{canUpdate&&<section className="card target-upload-card target-v3-upload"><div className="target-upload-title"><div><span className="target-v3-overline">BULK IMPORT</span><strong>Upload Target File</strong><span>RSO number or BP code + target type + target value</span></div><a href="/api/samples/targets" className="btn upload-sample-btn">Download Sample</a></div><div className="target-v3-flow"><span>Excel file</span><i>→</i><span>Validate rows</span><i>→</i><span>Apply to {month}</span></div><label className="upload-drop"><input type="file" accept=".xlsx,.xls,.xlsm" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?file.name:"Choose target Excel file"}</b><span>{file?`Ready for ${month}`:"XLSX / XLS / XLSM · max 20 MB"}</span></label><button className="btn admin-primary upload-process-btn" disabled={!file||uploading} onClick={upload}>{uploading?"Validating & Importing...":"Import Targets"}</button>{uploadResult&&<div className="target-import-result"><span>Total <b>{uploadResult.totalRows}</b></span><span>Updated <b>{uploadResult.updated}</b></span><span>Failed <b>{uploadResult.failed}</b></span>{uploadResult.errors?.length?<details><summary>View errors</summary>{uploadResult.errors.map((e:string)=><div key={e}>{e}</div>)}</details>:null}</div>}</section>}
  {message&&<PremiumFeedback message={message} tone={/failed|error|invalid/i.test(message)?"error":/complete|saved/i.test(message)?"success":"info"}/>}
  <div className="target-kpis premium-target-kpis">{[["GA",totals.ga],["C2C",totals.c2c],["SC",totals.sc],["Recharge",totals.recharge],["SSO",totals.sso],["LSO",totals.lso]].map(([l,v])=><div className="card" key={String(l)}><span>{l}</span><strong>{Number(v).toLocaleString()}</strong></div>)}</div>
  </div>
  <section className="section"><div className="target-section-head"><div><span>RSO TARGETS</span><h2>Employee Targets</h2></div><div className="target-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search RSO / supervisor"/></div></div><div className="target-mobile-list">{visible.map(r=>{const i=rows.findIndex(x=>x.employeeId===r.employeeId);return <article className="target-mobile-card" key={r.employeeId}><div className="target-mobile-head"><div><strong>{r.name}</strong><span>{r.employeeCode||r.rsoMsisdn} · {r.supervisor}</span></div><b>{r.retailerCount} retailers</b></div><div className="target-mobile-fields">{numericFields.map(k=><label key={k}><span>{k==="gaTarget"?"GA":k==="c2cTarget"?"C2C":k==="scTarget"?"SC":k==="totalRechargeTarget"?"Recharge":k==="ssoTarget"?"SSO":k==="lsoTarget"?"LSO":"SC Achieved"}</span>{canUpdate?<input type="number" min="0" value={r[k]} onChange={e=>update(i,k,e.target.value)}/>:<strong>{Number(r[k]).toLocaleString()}</strong>}</label>)}</div></article>})}</div><div className="card modern-table-wrap"><table><thead><tr><th>RSO</th><th>Supervisor</th><th>GA</th><th>C2C</th><th>SC</th><th>Total Recharge</th><th>SSO</th><th>LSO</th><th>SC Achieved</th></tr></thead><tbody>{visible.map(r=>{const i=rows.findIndex(x=>x.employeeId===r.employeeId);return <tr key={r.employeeId}><td><strong>{r.name}</strong><small>{r.rsoMsisdn} · {r.employeeCode||"-"}</small></td><td>{r.supervisor}</td>{numericFields.map(k=><td key={k}>{canUpdate?<input type="number" min="0" value={r[k]} onChange={e=>update(i,k,e.target.value)}/>:Number(r[k]).toLocaleString()}</td>)}</tr>})}</tbody></table></div><TableScrollHint/></section>
  <section className="section"><div className="target-section-head"><div><span>BP TARGETS</span><h2>BP Monthly GA Targets</h2></div></div><div className="target-mobile-list bp-target-mobile">{bpRows.map((r,i)=><article className="target-mobile-card" key={r.assignmentId}><div className="target-mobile-head"><div><strong>{r.bpName||r.bpCode}</strong><span>{r.bpCode} · RSO {r.rsoName}</span></div></div><label className="bp-target-field"><span>GA TARGET</span>{canUpdate?<input type="number" min="0" value={r.gaTarget} onChange={e=>setBpRows(v=>v.map((x,n)=>n===i?{...x,gaTarget:Math.max(0,Number(e.target.value)||0)}:x))}/>:<strong>{r.gaTarget}</strong>}</label></article>)}</div><div className="card modern-table-wrap"><table><thead><tr><th>BP Code</th><th>BP Name</th><th>RSO</th><th>GA Target</th></tr></thead><tbody>{bpRows.map((r,i)=><tr key={r.assignmentId}><td><strong>{r.bpCode}</strong></td><td>{r.bpName||"-"}</td><td>{r.rsoName}<small>{r.rsoMsisdn}</small></td><td>{canUpdate?<input type="number" min="0" value={r.gaTarget} onChange={e=>setBpRows(v=>v.map((x,n)=>n===i?{...x,gaTarget:Math.max(0,Number(e.target.value)||0)}:x))}/>:r.gaTarget}</td></tr>)}</tbody></table></div></section>
  {canUpdate&&<div className="target-save-bar"><span>{rows.length} RSO · {bpRows.length} BP records</span><button className="btn admin-primary" disabled={saving||loading} onClick={save}>{saving?"Saving...":"Save All Changes"}</button></div>}
 </main>
}
